version: "3.8"

services:
  postgresdb:
    image: postgres:16
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_DB: eval
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3valu4t10n
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-api
    depends_on:
      - postgresdb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/eval
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 3valu4t10n
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

volumes:
  postgres_data:
